version: '3'
services:
  anaconda1:
    build: .
    container_name: Data_Augmentation
    volumes:
      - ./data_aug:/app
    command: >
      /bin/bash -c "apt-get update && apt-get install -y libgl1-mesa-glx && pip install adversarial-robustness-toolbox && pip install opencv-python && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    networks:
      - my_network
  
  anaconda2:
    build: .
    container_name: Model_Similarity
    volumes:
      - ./model_similarity:/app
    command: >
      /bin/bash -c "apt-get update && apt-get install -y libgl1-mesa-glx && pip install adversarial-robustness-toolbox && pip install opencv-python && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    networks:
      - my_network
      
  anaconda3:
    build: .
    container_name: Evasion_Attack
    volumes:
      - ./evasion_atk:/app
    command: >
      /bin/bash -c "apt-get update && apt-get install -y libgl1-mesa-glx && pip install adversarial-robustness-toolbox && pip install opencv-python && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    networks:
      - my_network
      
  anaconda4:
    build: .
    container_name: Feature_Collision_Attack
    volumes:
      - ./feature_col:/app
    command: >
      /bin/bash -c "apt-get update && apt-get install -y libgl1-mesa-glx && pip install adversarial-robustness-toolbox && pip install opencv-python && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    networks:
      - my_network
      
  anaconda5:
    build: .
    container_name: Hidden_Backdoor_Attack
    volumes:
      - ./hidden_backdoor:/app
    command: >
      /bin/bash -c "apt-get update && apt-get install -y libgl1-mesa-glx && pip install adversarial-robustness-toolbox && pip install opencv-python && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    networks:
      - my_network
      
networks:
  my_network:
